### ISSUE TITLE
jQuery dependent components

### ISSUE THREAD

**Issue by idursun** [circuithub/elm-semantic-ui#1]
Hi, 
Do you have any plans for creating equivalents of jQuery dependent components of Semantic UI (e.g. dropdown)? or do you just plan to leave them out and just import the ones that are based on plain html + css ?

**Comment by ocharles** [comment]
We're unsure at the moment. Right now, the focus is on just the pure HTML side.

**Comment by ocharles** [comment]
Closing as there is nothing "to do" right now, but not because I don't want to keep this dialog open. If you have thoughts, let me know!
