### ISSUE TITLE
How to use with Elm 0.19?

### ISSUE THREAD

**Issue by domenkozar** [circuithub/elm-semantic-ui#8]
Hey @ocharles,

I've been eyeing to use this library and want contribute back. I guess the main reason holding me back is that it's not easy to use it as it's not released.

How do you use it, especially now that elm-github-install is gone?

**Comment by ocharles** [comment]
We are just using it as a submodule at work. I don't know anything more about packaging Elm modules.

**Comment by domenkozar** [comment]
That should work - thanks

**Comment by ocharles** [comment]
If releasing it would be easier for you, I'm happy to start cutting releases. Let me know how you get on!

**Comment by domenkozar** [comment]
I'll give it a try with submodules first and let you know if it means trouble.
